package com.mehrrizwan.lib.keyvaluestore.greendao;

import android.database.sqlite.SQLiteDatabase;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapDaoConfig;

    private final MapDao mapDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, java.util.Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapDaoConfig = daoConfigMap.get(MapDao.class).clone();
        mapDaoConfig.initIdentityScope(type);

        mapDao = new MapDao(mapDaoConfig, this);

        registerDao(Map.class, mapDao);
    }
    
    public void clear() {
        mapDaoConfig.getIdentityScope().clear();
    }

    public MapDao getMapDao() {
        return mapDao;
    }

}
